
# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- ../../../base/web

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: localhost:5000/roar-web
  newTag: 0.0.48
