
# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- ../../../base/db

# Add in persistent storage
patchesStrategicMerge:
- patch_pv.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: localhost:5000/roar-db
  newTag: 1.0.56
