apiVersion: apps/v1
kind: Deployment
metadata:
  name: roar-web
spec:
  template:
    spec:
      containers:
      - name: roar-web
        env:
        - name: MYSQL_ENV_MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-db-configmap
              key: mysql.database
      
